name: Deploy lambda

on:
  push:
    branches:
      - develop

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: go to lambda directory
        run: cd packages/serverless
      - name: npm install
        env:
          CI: true
        run: npm ci
