version: 0.2
phases:
  pre_build:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing npm dependencies"
      - npm install
  build:
    commands:
      - echo "Zipping deployment package"
      - zip -r files.zip .
  post_build:
    commands:
      - echo "Updating lambda function"
      - aws lambda update-function-code --function-name budgeto-login --zip-file fileb://files.zip
      - echo "Done!"
